# Generated by Django 5.1.7 on 2025-04-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_image_remove_skill_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='github_link',
            new_name='demo_url',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='live_link',
            new_name='github_url',
        ),
        migrations.AddField(
            model_name='project',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='planning', max_length=20),
        ),
    ]
